### ISSUE TITLE
Fedora 27:  project will not build

### ISSUE THREAD

**Issue by ajvincent** [ckane/expatmm#1]
```
[ajvincent@localhost foo]$ git clone https://github.com/ckane/expatmm.git
[ajvincent@localhost foo]$ cd expatmm/
[ajvincent@localhost expatmm]$ ./autogen.sh 
[ajvincent@localhost expatmm]$ ./configure
[ajvincent@localhost expatmm]$ make

Making all in src
make[1]: Entering directory '/home/ajvincent/verbosio/expatmm/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../include -I../include     -g -O2 -MT ExpatXMLParser.lo -MD -MP -MF .deps/ExpatXMLParser.Tpo -c -o ExpatXMLParser.lo ExpatXMLParser.cpp
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1.11, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1.11
libtool: and run autoconf again.
make[1]: *** [Makefile:446: ExpatXMLParser.lo] Error 63
make[1]: Leaving directory '/home/ajvincent/verbosio/expatmm/src'
make: *** [Makefile:465: all-recursive] Error 1
```

Please advise.  (I'm interested in using this library and compiling it to WebAssembly, where it can be called from JavaScript.)

**Comment by ckane** [comment]
Thanks for the issue submission - I'll try building using Fedora 27 in a VM sometime this week and see if I can reproduce. Looks to me like there might be some portion of my libtool macros in the git repo.

**Comment by ckane** [comment]
@ajvincent can you try again using the latest code in the master branch? I've removed ltmain.sh and call libtoolize from autogen.sh to initialize the build now. This should cause it to use whatever libtool version you have installed.

**Comment by ajvincent** [comment]
That works, thanks.

**Comment by ckane** [comment]
Awesome, I'll tag a new release in January with this change (and anything else that comes up before then).
