### ISSUE TITLE
MacOS 10.13.2:  project will not build

### ISSUE THREAD

**Issue by ajvincent** [ckane/expatmm#2]
> ./autogen.sh: line 9: libtoolize: command not found
> configure.ac:19: installing './compile'
> configure.ac:14: installing './config.guess'
> configure.ac:14: installing './config.sub'
> configure.ac:17: installing './install-sh'
> configure.ac:31: error: required file './ltmain.sh' not found
> configure.ac:17: installing './missing'
> src/Makefile.am: installing './depcomp'

https://stackoverflow.com/questions/15448582/installed-libtool-but-libtoolize-not-found

**Comment by ckane** [comment]
I noticed you have some commits in your own fork - do you mind if I merge these into the main project?
Do your commits resolve the issue above?

**Comment by ajvincent** [comment]
You are most certainly welcome to merge my changes, but no, they do not resolve the reported problem.  The commit logs show that those changes are for other things.

**Comment by ckane** [comment]
Ok thanks - I had a chance to look into it further and I guess these are installed as <code>glibtool</code> / <code>glibtoolize</code> on Mac w/ Xcode? I presume to note that they are GNU tools.

**Comment by ckane** [comment]
@ajvincent let me know if the changes in the **mac-libtool-fix** branch works correctly for you

**Comment by ckane** [comment]
Merged #4
