### ISSUE TITLE
Cannot build project on Windows 10

### ISSUE THREAD

**Issue by ectil** [ckane/expatmm#3]
I'm very new to using open source packages and have been unable to build the package using MinGW/msys on Windows 10

Any help is greatly appreciated!

$ ./autogen.sh
./autogen.sh: line 9: libtoolize: command not found
./autogen.sh: line 12: --foreign: command not found
./autogen.sh: line 13: --include=../include: No such file or directory

**Comment by ectil** [comment]
My apologies, the error is actually:

$ ./configure
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking target system type... i686-pc-mingw32
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... none
checking for ranlib... ranlib
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/c/Users/litce/Documents/CodeBlocks/~lib/expatmm-master':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

**Comment by ectil** [comment]
My apologies for the continued comments. The error above was quickly resolved by adding the g++ compiler to MinGW. 

After this, I received the error below when running ./configure:

error: *** libexpat.so not found! Please ensure it is in your search path. ***

Looking at the config.log file shows that this error occurs after g++ throws the following error:

g++.exe: error: unrecognized command line option '-no-undefined'; did you mean '-Wno-undef'?

I'm unsure why this flag is needed and resolved the issue by changing the the configure script to return no when checking if the-no-undefined flag is needed:

  { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether ${host} needs -no-undefined at link time" >&5
$as_echo_n "checking whether ${host} needs -no-undefined at link time... " >&6; }
  case $host in
    *-mingw32)
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "no" >&6; }
        #LDFLAGS="$LDFLAGS -no-undefined" # TESTING for MINGW32
        ;;
    *)
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
        ;;
  esac

**Comment by morganmcleod** [comment]
I seem to be having the same or a similar problem.    Attempting to build on Win7 with 32-bit MingW:

checking stdio.h presence... yes
checking for stdio.h... yes
checking for string.h... (cached) yes
checking string usability... yes
checking string presence... yes
checking for string... yes
no
configure: error: *** libexpat.so not found! Please ensure it is in your search path. ***

MingW does not include libexpat.so (or any .so files.)   It has libexpat-1.dll, libexpat.a, and libexpat.dll.a.

I don't have any experience troubleshooting autotools scripts.   

Any suggestions?    Thanks.

**Comment by morganmcleod** [comment]
I got it to build and be usable by hacking the configure script to not perform that test and just to set:
LIBS="$LIBS -lexpat"

Obviously not the best solution but I can proceed for now.   Still interested in doing it the right way if possible.

**Comment by ckane** [comment]
Thanks - yes the problem described above would need to be resolved by also downloading the source code for Expat (https://libexpat.github.io/) and building and installing that onto your MinGW/MSYS environment first. After that, you'll build and install this package, which depends upon Expat.

This would be the "right way" for MinGW/MSYS. Not sure if they have a binary package distributing the "-dev" files, in addition to the binary libraries. When I wrote the library long ago targeting MinGW32, packages for expat weren't distributed for the MinGW/MSYS package.

**Comment by ckane** [comment]
Closing this as no response for 10 months
